"use client";
import { useCallback, useState } from "react";
import type { RedemptionDto, RewardDto, RewardOptionDto, TransactionDto } from "@/lib/contracts";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { mentorRequest } from "./api";
import { TextField } from "./form-fields";
import { useMutation, usePagedResource, useResource } from "./hooks";
import { dateLabel, EmptyState, ErrorNotice, humanize, LoadingState, PageHeader, StatusMark, SuccessNotice } from "./ui";

export function BalanceView() {
  const load = useCallback(() => mentorRequest("balance.get", {}), []); const resource = useResource(load);
  const data = resource.data;
  return <><PageHeader title="Balance" description="Your credits and recognition for mentoring." /><ErrorNotice error={resource.error} retry={resource.reload} />{resource.loading ? <LoadingState label="Loading your balance…" /> : data ? <>
    <dl className="balance-summary"><div><dt>Available balance</dt><dd>{data.balance}<span> points</span></dd></div><div><dt>Reserved for requests</dt><dd>{data.reserved}<span> points</span></dd></div><div><dt>Total credits earned</dt><dd>{data.totalCredit}<span> points</span></dd></div><div><dt>Rounds completed</dt><dd>{data.roundCount}</dd></div></dl>
    <section className="content-section"><div className="section-toolbar"><h2>Leader board</h2></div>{data.ranking?.length ? <div className="data-table"><Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Mentor</TableHead><TableHead>Rounds</TableHead><TableHead>Groups</TableHead><TableHead>Points</TableHead></TableRow></TableHeader><TableBody>{data.ranking.map(item => <TableRow key={`${item.rank}-${item.mentorName}`}><TableCell>{item.rank}</TableCell><TableCell><strong>{item.mentorName}</strong>{item.isCurrentMentor ? <span className="cell-secondary">You</span> : null}</TableCell><TableCell>{item.roundCount}</TableCell><TableCell>{item.groupCount}</TableCell><TableCell>{item.currentCredit}</TableCell></TableRow>)}</TableBody></Table></div> : <EmptyState title="Ranking is not available">Your personal balance is shown above. Ranking appears when it is provided by the programme.</EmptyState>}</section>
    <section className="content-section"><div className="section-toolbar"><h2>Reward points criteria</h2></div><p className="section-description">These criteria explain how points can be awarded. Programme review determines each award.</p>{data.creditCriteria?.length ? <div className="data-table"><Table className="criteria-table"><TableHeader><TableRow><TableHead>Category</TableHead><TableHead>Criteria and details</TableHead><TableHead>Points</TableHead></TableRow></TableHeader><TableBody>{data.creditCriteria.map((item, index) => <TableRow key={`${item.category}-${index}`}><TableCell>{item.category}</TableCell><TableCell>{item.label}</TableCell><TableCell>{item.points}{item.cadence ? ` ${item.cadence}` : ""}</TableCell></TableRow>)}</TableBody></Table></div> : <EmptyState title="Criteria are not available">Contact Support for the current points criteria.</EmptyState>}</section>
  </> : null}</>;
}
export function TransactionsView() {
  const load = useCallback((cursor?: string) => mentorRequest("transactions.list", { ...(cursor ? { cursor } : {}), limit: 25 }), []); const resource = usePagedResource(load); const [selected, setSelected] = useState<TransactionDto | null>(null);
  return <><PageHeader title="Transactions" description="A record of your credit activity." /><ErrorNotice error={resource.error} retry={resource.reload} />{resource.loading ? <LoadingState label="Loading transactions…" /> : resource.data?.items.length ? <div className="data-table"><Table><TableHeader><TableRow><TableHead>Transaction</TableHead><TableHead>Date</TableHead><TableHead>Group</TableHead><TableHead>Points</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{resource.data.items.map(item => <TableRow key={item.id}><TableCell><strong>{item.type}</strong><span className="cell-secondary">{item.transactionId}</span></TableCell><TableCell>{dateLabel(item.timestamp)}</TableCell><TableCell>{item.group || "—"}</TableCell><TableCell><strong>{item.amount > 0 ? "+" : ""}{item.amount}</strong></TableCell><TableCell><Button variant="outline" onClick={() => setSelected(item)}>Details</Button></TableCell></TableRow>)}</TableBody></Table></div> : !resource.error ? <EmptyState title="No transactions yet">Your credit awards and reward requests will appear here.</EmptyState> : null}<ErrorNotice error={resource.pageError} retry={resource.more} />{resource.data?.nextCursor ? <div className="load-more"><Button variant="outline" onClick={resource.more} disabled={resource.loadingMore}>{resource.loadingMore ? "Loading…" : "Load more transactions"}</Button></div> : null}<Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent><DialogHeader><DialogTitle>Transaction details</DialogTitle><DialogDescription>{selected?.transactionId}</DialogDescription></DialogHeader>{selected ? <dl className="record-details"><div><dt>Type</dt><dd>{selected.type}</dd></div><div><dt>Points</dt><dd>{selected.amount > 0 ? "+" : ""}{selected.amount}</dd></div><div><dt>Date</dt><dd>{dateLabel(selected.timestamp)}</dd></div><div><dt>Issuer</dt><dd>{selected.issuer || "—"}</dd></div><div><dt>Notes</dt><dd>{selected.notes || "No additional notes."}</dd></div></dl> : null}</DialogContent></Dialog></>;
}
export function StoreView() {
  const loadRewards = useCallback((cursor?: string) => mentorRequest("rewards.list", { ...(cursor ? { cursor } : {}), limit: 25 }), []);
  const loadRequests = useCallback((cursor?: string) => mentorRequest("redemptions.list", { ...(cursor ? { cursor } : {}), limit: 25 }), []);
  const loadBalance = useCallback(() => mentorRequest("balance.get", {}), []);
  const rewards = usePagedResource(loadRewards); const requests = usePagedResource(loadRequests); const balance = useResource(loadBalance);
  const [selected, setSelected] = useState<RewardDto | null>(null);
  function saved() { void balance.reload(); void requests.reload(); void rewards.reload(); }
  return <><PageHeader title="Credit Store" description="Choose a reward for your mentoring contribution."><p className="balance-inline">Available: <strong>{balance.loading ? "…" : balance.data?.balance ?? "—"} points</strong></p></PageHeader><ErrorNotice error={rewards.error || balance.error} retry={() => { void rewards.reload(); void balance.reload(); }} />
    {rewards.loading ? <LoadingState label="Loading rewards…" /> : rewards.data?.items.length ? <div className="data-table"><Table><TableHeader><TableRow><TableHead>Reward</TableHead><TableHead>Points</TableHead><TableHead>Availability</TableHead><TableHead><span className="sr-only">Select reward</span></TableHead></TableRow></TableHeader><TableBody>{rewards.data.items.map(reward => <TableRow key={reward.id}><TableCell><strong>{reward.name}</strong><span className="cell-secondary">{reward.productType}</span></TableCell><TableCell>{reward.discountPoints !== null && reward.effectivePoints !== reward.points ? <><del className="muted">{reward.points}</del> </> : null}<strong>{reward.effectivePoints}</strong></TableCell><TableCell><StatusMark complete={reward.inStock} dot>{reward.inStock ? "In stock" : "Unavailable"}</StatusMark></TableCell><TableCell><Button variant="outline" onClick={() => setSelected(reward)} disabled={!reward.inStock}>View reward</Button></TableCell></TableRow>)}</TableBody></Table></div> : !rewards.error ? <EmptyState title="No rewards available">Check back when new rewards are added.</EmptyState> : null}
    <ErrorNotice error={rewards.pageError} retry={rewards.more} />{rewards.data?.nextCursor ? <div className="load-more"><Button variant="outline" onClick={rewards.more} disabled={rewards.loadingMore}>Load more rewards</Button></div> : null}
    <section className="content-section"><div className="section-toolbar"><h2>Your reward requests</h2></div><p className="section-description">A pending request is awaiting review and has not been approved or fulfilled.</p><ErrorNotice error={requests.error || requests.pageError} retry={requests.reload} />{requests.loading ? <LoadingState label="Loading reward requests…" /> : requests.data?.items.length ? <div className="data-table"><Table><TableHeader><TableRow><TableHead>Reward and reference</TableHead><TableHead>Requested</TableHead><TableHead>Points</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{requests.data.items.map(request => <TableRow key={request.id}><TableCell><strong>{request.rewardName}</strong><span className="cell-secondary">{request.requestReference}</span></TableCell><TableCell>{dateLabel(request.createdAt)}</TableCell><TableCell>{request.points}<span className="cell-secondary">{humanize(request.creditState)}</span></TableCell><TableCell><StatusMark complete={request.status === "approved"}>{humanize(request.status)}</StatusMark></TableCell></TableRow>)}</TableBody></Table></div> : !requests.error ? <EmptyState title="No reward requests yet">Your requests and their progress will appear here.</EmptyState> : null}{requests.data?.nextCursor ? <div className="load-more"><Button variant="outline" onClick={requests.more} disabled={requests.loadingMore}>Load more requests</Button></div> : null}</section>
    <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>Choose your options and review the points required.</DialogDescription></DialogHeader>{selected ? <RewardRequest key={selected.id} rewardId={selected.id} balance={balance.data?.balance} onSaved={saved} /> : null}</DialogContent></Dialog>
  </>;
}
function RewardRequest({ rewardId, balance, onSaved }: { rewardId: string; balance?: number; onSaved: () => void }) {
  const load = useCallback(() => mentorRequest("rewards.get", { rewardId }), [rewardId]); const resource = useResource(load);
  if (resource.loading) return <LoadingState label="Loading reward options…" />;
  if (!resource.data) return <ErrorNotice error={resource.error} retry={resource.reload} />;
  return <RewardRequestForm reward={resource.data.reward} options={resource.data.options} balance={balance} onSaved={onSaved} />;
}
function RewardRequestForm({ reward, options, balance, onSaved }: { reward: RewardDto; options: RewardOptionDto[]; balance?: number; onSaved: () => void }) {
  const types = [...new Set(options.map(option => option.type))];
  const [selected, setSelected] = useState<Record<string, string>>({}); const [comment, setComment] = useState(""); const [receipt, setReceipt] = useState<RedemptionDto | null>(null); const mutation = useMutation();
  const enough = balance !== undefined && balance >= reward.effectivePoints;
  const available = reward.inStock && types.every(type => options.some(option => option.type === type && option.inStock && option.extraCost === 0));
  async function submit(event: React.FormEvent) { event.preventDefault(); const result = await mutation.run("redemptions.create", { rewardId: reward.id, optionIds: Object.values(selected).filter(Boolean), comment }); if (result) { setReceipt(result.redemption); onSaved(); } }
  if (receipt) return <div className="form-stack"><SuccessNotice>Your request was recorded and is {humanize(receipt.status).toLowerCase()}.</SuccessNotice><dl className="record-details"><div><dt>Request reference</dt><dd>{receipt.requestReference}</dd></div><div><dt>Points</dt><dd>{receipt.points} · {humanize(receipt.creditState)}</dd></div><div><dt>Next step</dt><dd>You can follow its status in Your reward requests.</dd></div></dl></div>;
  return <form onSubmit={submit}><FieldGroup><dl className="record-details"><div><dt>Points required</dt><dd>{reward.effectivePoints}</dd></div><div><dt>Your available balance</dt><dd>{balance ?? "Unavailable"}</dd></div></dl>{types.map(type => <Field key={type}><FieldLabel htmlFor={`reward-${type}`}>{type} *</FieldLabel><NativeSelect id={`reward-${type}`} required value={selected[type] || ""} onChange={e => setSelected(previous => ({ ...previous, [type]: e.target.value }))} disabled={mutation.pending || mutation.readOnly}><NativeSelectOption value="" disabled>Choose {type.toLowerCase()}</NativeSelectOption>{options.filter(option => option.type === type).map(option => <NativeSelectOption key={option.id} value={option.id} disabled={!option.inStock || option.extraCost !== 0}>{option.label}{!option.inStock || option.extraCost !== 0 ? " — unavailable" : ""}</NativeSelectOption>)}</NativeSelect></Field>)}<TextField label="Request comments" value={comment} onChange={setComment} multiline maxLength={1000} description="Optional" disabled={mutation.pending || mutation.readOnly} /><p className="form-hint">Your request will be sent for review. Points may be reserved while it is pending.</p>{!enough ? <p className="form-hint">{balance === undefined ? "Your balance must be available before requesting this reward." : "You do not have enough available points for this reward."}</p> : null}{!available ? <p className="form-hint">This reward or its options are currently unavailable.</p> : null}<ErrorNotice error={mutation.error} /></FieldGroup><div className="form-actions"><Button disabled={mutation.pending || !enough || !available || mutation.readOnly}>{mutation.pending ? "Recording request…" : `Request reward · ${reward.effectivePoints} points`}</Button></div></form>;
}
