"use client";
import { useCallback, useState } from "react";
import type { AttachmentDto, ExpenseDto, GroupDto, ReportDto, ReportKind } from "@/lib/contracts";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Attachments } from "./attachments";
import { mentorRequest } from "./api";
import { CheckField, TextField } from "./form-fields";
import { reportLabels, type ReportSelection } from "./groups";
import { useMutation, usePagedResource, useResource } from "./hooks";
import { useSession } from "./session";
import { dateLabel, EmptyState, ErrorNotice, humanize, LoadingState, PageHeader, StatusMark, SuccessNotice } from "./ui";

export function ReportsView({ groups, onReport, revision = 0 }: { groups: GroupDto[]; onReport: (selection: ReportSelection) => void; revision?: number }) {
  const [groupId, setGroupId] = useState(groups[0]?.id || ""); const [kind, setKind] = useState(""); const [newOpen, setNewOpen] = useState(false);
  const load = useCallback((cursor?: string) => groupId ? mentorRequest("reports.list", { groupId, ...(kind ? { kind: kind as ReportKind } : {}), ...(cursor ? { cursor } : {}), limit: 25 }) : Promise.resolve({ items: [] as ReportDto[], nextCursor: null }), [groupId, kind]);
  const resource = usePagedResource(load, revision);
  return <><PageHeader title="Reports" description="Prepare and review your mentoring reports."><Button onClick={() => setNewOpen(true)} disabled={!groups.find(group => group.id === groupId)?.reportEnabled}>Start a report</Button></PageHeader><div className="filter-row"><Field><FieldLabel htmlFor="reports-group">Group</FieldLabel><NativeSelect id="reports-group" disabled={!groups.length} value={groupId} onChange={e => setGroupId(e.target.value)}>{groups.map(group => <NativeSelectOption key={group.id} value={group.id}>{group.title}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="reports-kind">Report type</FieldLabel><NativeSelect id="reports-kind" value={kind} onChange={e => setKind(e.target.value)}><NativeSelectOption value="">All report types</NativeSelectOption>{Object.entries(reportLabels).map(([value, label]) => <NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></Field></div><ErrorNotice error={resource.error} retry={resource.reload} />
    {resource.loading ? <LoadingState label="Loading reports…" /> : resource.data?.items.length ? <div className="data-table"><Table><TableHeader><TableRow><TableHead>Report</TableHead><TableHead>Group</TableHead><TableHead>Status</TableHead><TableHead>Last updated</TableHead><TableHead><span className="sr-only">Action</span></TableHead></TableRow></TableHeader><TableBody>{resource.data.items.map(report => <TableRow key={report.id}><TableCell><strong>{reportLabels[report.kind]}</strong>{report.title ? <span className="cell-secondary">{report.title}</span> : null}</TableCell><TableCell>{groups.find(group => group.id === report.groupId)?.title || "Assigned group"}</TableCell><TableCell><StatusMark complete={report.submissionState === "submitted"}>{humanize(report.submissionState)}</StatusMark></TableCell><TableCell>{dateLabel(report.modifiedAt || report.createdAt)}</TableCell><TableCell><Button variant="outline" onClick={() => { const group = groups.find(item => item.id === report.groupId); if (group) onReport({ group, kind: report.kind, report }); }} disabled={!groups.some(group => group.id === report.groupId)}>{report.submissionState === "submitted" || report.submissionState === "unknown" ? "View report" : "Continue report"}</Button></TableCell></TableRow>)}</TableBody></Table></div> : !resource.error ? <EmptyState title={groups.length ? "No reports here yet" : "No groups assigned"}>{groups.length ? "Start a report for this group, or choose another filter." : "Your reports will appear when a mentoring group is assigned to you."}</EmptyState> : null}
    <ErrorNotice error={resource.pageError} retry={resource.more} />{resource.data?.nextCursor ? <div className="load-more"><Button variant="outline" onClick={resource.more} disabled={resource.loadingMore}>{resource.loadingMore ? "Loading…" : "Load more reports"}</Button></div> : null}
    <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent><DialogHeader><DialogTitle>Start a report</DialogTitle><DialogDescription>Choose the group and report you want to prepare.</DialogDescription></DialogHeader>{newOpen ? <NewReportChooser groups={groups} defaultGroupId={groupId} start={selection => { setNewOpen(false); onReport(selection); }} /> : null}</DialogContent></Dialog>
  </>;
}
function NewReportChooser({ groups, defaultGroupId, start }: { groups: GroupDto[]; defaultGroupId: string; start: (selection: ReportSelection) => void }) {
  const [groupId, setGroupId] = useState(defaultGroupId || groups[0]?.id || ""); const [kind, setKind] = useState<ReportKind>("week1"); const [error, setError] = useState<Error | null>(null); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(null); try { const result = await mentorRequest("groups.get", { groupId }); start({ group: result.group, kind, report: result.reports.find(report => report.kind === kind && report.submissionState !== "submitted") || (kind !== "meetup" ? result.reports.find(report => report.kind === kind) : undefined) }); } catch (e) { setError(e as Error); setPending(false); } }
  return <form onSubmit={submit}><FieldGroup><Field><FieldLabel htmlFor="new-report-group">Group</FieldLabel><NativeSelect id="new-report-group" value={groupId} onChange={e => setGroupId(e.target.value)} disabled={pending}>{groups.filter(group => group.reportEnabled).map(group => <NativeSelectOption key={group.id} value={group.id}>{group.title}</NativeSelectOption>)}</NativeSelect></Field><Field><FieldLabel htmlFor="new-report-kind">Report type</FieldLabel><NativeSelect id="new-report-kind" value={kind} onChange={e => setKind(e.target.value as ReportKind)} disabled={pending}>{Object.entries(reportLabels).map(([value, label]) => <NativeSelectOption key={value} value={value}>{label}</NativeSelectOption>)}</NativeSelect></Field><ErrorNotice error={error} /></FieldGroup><div className="form-actions"><Button disabled={pending || !groupId}>{pending ? "Opening…" : "Continue"}</Button></div></form>;
}

export function ReportDialog({ selection, close, onSaved }: { selection: ReportSelection | null; close: () => void; onSaved: () => void }) {
  return <Dialog open={!!selection} onOpenChange={open => { if (!open) close(); }}><DialogContent className="report-dialog"><DialogHeader><DialogTitle>{selection ? reportLabels[selection.kind] : ""} report</DialogTitle><DialogDescription>{selection?.group.title} · {selection?.group.roundId}</DialogDescription></DialogHeader>{selection ? <ReportEditor key={`${selection.group.id}-${selection.kind}-${selection.report?.id || "new"}`} selection={selection} onSaved={onSaved} /> : null}</DialogContent></Dialog>;
}
function ReportEditor({ selection, onSaved }: { selection: ReportSelection; onSaved: () => void }) {
  const { session } = useSession(); const { group, kind } = selection;
  const [current, setCurrent] = useState(selection.report); const [version, setVersion] = useState(selection.report?.version);
  const [question, setQuestion] = useState(current?.question || ""); const [flag, setFlag] = useState(current?.flagComment || "");
  const [title, setTitle] = useState(current?.title || ""); const [otherGroup, setOtherGroup] = useState(current?.otherGroup || "");
  const [date, setDate] = useState(current?.meetupDate || ""); const [attendance, setAttendance] = useState(String(current?.attendance ?? "")); const [description, setDescription] = useState(current?.description || "");
  const [giftCard, setGiftCard] = useState(current?.isUseGC || false); const [special, setSpecial] = useState(current?.isRequiredSC || false); const [specialComment, setSpecialComment] = useState(current?.scComment || "");
  const [takeaways, setTakeaways] = useState(current?.keyTakeaways || ""); const [helpful, setHelpful] = useState(current?.mostHelpful || ""); const [again, setAgain] = useState(current?.isJointAgain ?? true);
  const [files, setFiles] = useState<AttachmentDto[]>(current?.attachments || []); const [uploading, setUploading] = useState(false); const [saved, setSaved] = useState(""); const [localError, setLocalError] = useState<Error | null>(null);
  const mutation = useMutation(); const readOnly = current?.submissionState === "submitted" || current?.submissionState === "unknown"; const busy = mutation.pending || uploading;
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLocalError(null); setSaved("");
    const submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null;
    const submit = submitter?.value !== "draft";
    if (kind === "meetup" && submit && !files.some(file => file.mimeType.startsWith("image/"))) { setLocalError(new Error("Upload at least one group photo before submitting the meet-up report.")); return; }
    const edit = { groupId: group.id, ...(current ? { reportId: current.id, expectedVersion: version } : {}), submit };
    let result: { report: ReportDto; group: GroupDto } | null = null;
    if (kind === "week1") result = await mutation.run("reports.week1.save", { ...edit, question, flagComment: flag });
    if (kind === "meetup") result = await mutation.run("reports.meetup.save", { ...edit, title, otherGroup, meetupDate: date, attendance: Number(attendance), description, isUseGC: giftCard, isRequiredSC: special, scComment: specialComment, attachmentIds: files.map(file => file.id) });
    if (kind === "completion") result = await mutation.run("reports.completion.save", { ...edit, keyTakeaways: takeaways, mostHelpful: helpful, isJointAgain: again, flagComment: flag });
    if (result) { setCurrent(result.report); setVersion(result.report.version); setFiles(result.report.attachments); setSaved(submit ? "Your report has been submitted. It is awaiting review." : "Your draft is saved. You can return to it from Reports."); onSaved(); }
  }
  if (readOnly) return <div className="form-stack">{saved ? <SuccessNotice>{saved}</SuccessNotice> : <StatusMark complete={current.submissionState === "submitted"}>{current.submissionState === "unknown" ? "Submission not confirmed" : "Submitted"} · {humanize(current.reviewStatus)}</StatusMark>}<ReportDetails report={current} /><Attachments context={{ parentKind: "meetupReport", parentId: current.id, groupId: group.id }} files={files} readOnly />{current.kind === "meetup" && current.isUseGC ? <ExpenseSection group={group} report={current} /> : null}</div>;
  return <form className="form-stack" onSubmit={submit}>{saved ? <SuccessNotice>{saved}</SuccessNotice> : null}<p className="form-hint">Fields marked * are required.</p><FieldGroup>
    {kind === "week1" ? <><TextField label="How did you support your mentees this week? What question from your mentees impressed you the most?" value={question} onChange={setQuestion} multiline required maxLength={5000} disabled={busy} /><TextField label="Is there anything you would like to flag based on your experience this week?" value={flag} onChange={setFlag} multiline maxLength={5000} disabled={busy} description="Optional" /></> : null}
    {kind === "meetup" ? <><TextField label="What did you do?" value={title} onChange={setTitle} required maxLength={200} disabled={busy} /><TextField label="Other collaborating groups" value={otherGroup} onChange={setOtherGroup} maxLength={200} disabled={busy} description="Optional — list any groups that joined you." /><div className="form-grid"><TextField label="Meet-up date" value={date} onChange={setDate} type="date" required disabled={busy} /><TextField label="Total attendance" value={attendance} onChange={setAttendance} type="number" min="0" max="500" step="1" required disabled={busy} description="Count yourself and your mentees only." /></div><TextField label="How was your meet-up? Where was it located?" value={description} onChange={setDescription} multiline required maxLength={10000} disabled={busy} /><Attachments context={{ parentKind: "meetupReport", groupId: group.id, ...(current ? { parentId: current.id, version } : {}) }} files={files} onChange={setFiles} onVersion={setVersion} onBusy={setUploading} photoOnly disabled={mutation.pending} label="Group photo *" /><p className="form-hint">Upload a photo only when the mentors and mentees pictured have agreed to its internal use by the programme.</p><CheckField label="I spent a gift card at this meet-up" checked={giftCard} onChange={setGiftCard} disabled={busy} />{giftCard ? <p className="form-hint">After submitting this report, add your expense amount and tax invoice.</p> : null}<CheckField label="I need special consideration" checked={special} onChange={setSpecial} disabled={busy} />{special ? <TextField label="Special consideration comment" value={specialComment} onChange={setSpecialComment} multiline required maxLength={5000} disabled={busy} /> : null}</> : null}
    {kind === "completion" ? <><TextField label="Please share your key takeaways from your experience." value={takeaways} onChange={setTakeaways} multiline required maxLength={10000} disabled={busy} /><TextField label="What helped your mentees the most throughout the programme?" value={helpful} onChange={setHelpful} multiline required maxLength={5000} disabled={busy} description="For example, answering questions or organising meet-ups." /><CheckField label="I would like to be involved in the programme again" checked={again} onChange={setAgain} disabled={busy} /><TextField label="Is there anything you would like to flag based on your experience in this programme?" value={flag} onChange={setFlag} multiline maxLength={5000} disabled={busy} description="Optional" /></> : null}
    <ErrorNotice error={localError || mutation.error} /></FieldGroup><div className="form-actions">{session?.mode === "demo" ? <Button type="submit" name="action" value="draft" variant="outline" disabled={busy}>Save draft</Button> : null}<Button type="submit" name="action" value="submit" disabled={busy}>{mutation.pending ? "Saving report…" : "Submit report"}</Button></div></form>;
}
function ReportDetails({ report }: { report: ReportDto }) {
  const fields = report.kind === "week1" ? [["Support and questions", report.question], ["Additional comments", report.flagComment]] : report.kind === "completion" ? [["Key takeaways", report.keyTakeaways], ["What helped most", report.mostHelpful], ["Interested in joining again", report.isJointAgain ? "Yes" : "No"], ["Additional comments", report.flagComment]] : [["Activity", report.title], ["Meet-up date", dateLabel(report.meetupDate)], ["Attendance", String(report.attendance ?? "—")], ["Description and location", report.description], ["Collaborating groups", report.otherGroup], ["Gift card used", report.isUseGC ? "Yes" : "No"], ["Special consideration", report.isRequiredSC ? report.scComment || "Requested" : "Not requested"]];
  return <dl className="record-details">{fields.filter(([, value]) => value).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>;
}
function ExpenseSection({ group, report }: { group: GroupDto; report: ReportDto }) {
  const load = useCallback(() => mentorRequest("groups.get", { groupId: group.id }), [group.id]); const resource = useResource(load);
  if (resource.loading) return <LoadingState label="Loading expenses…" />;
  if (resource.error) return <ErrorNotice error={resource.error} retry={resource.reload} />;
  const expenses = resource.data?.expenses.filter(expense => expense.meetupReportId === report.id) || [];
  return <section className="form-section"><h3>Meet-up expense</h3>{expenses.length ? expenses.map(expense => <ExpenseDetails key={expense.id} expense={expense} />) : <ExpenseForm group={group} report={report} saved={resource.reload} />}</section>;
}
function ExpenseDetails({ expense }: { expense: ExpenseDto }) { return <div className="form-stack"><dl className="record-details"><div><dt>Amount paid</dt><dd>{new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" }).format(expense.amount)}</dd></div><div><dt>Receipt status</dt><dd>{humanize(expense.reviewStatus)} · {humanize(expense.processingStatus)}</dd></div></dl><Attachments context={{ parentKind: "expense", parentId: expense.id, groupId: expense.groupId }} files={expense.attachments} readOnly label="Tax invoice" /></div>; }
function ExpenseForm({ group, report, saved }: { group: GroupDto; report: ReportDto; saved: () => Promise<void> }) {
  const [amount, setAmount] = useState(""); const [files, setFiles] = useState<AttachmentDto[]>([]); const [uploading, setUploading] = useState(false); const [error, setError] = useState<Error | null>(null); const mutation = useMutation();
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(null); if (!files.length) { setError(new Error("Upload your tax invoice before submitting the expense.")); return; } const result = await mutation.run("expenses.save", { groupId: group.id, meetupReportId: report.id, amount: Number(amount), attachmentIds: files.map(file => file.id) }); if (result) await saved(); }
  return <form onSubmit={submit}><FieldGroup><TextField label="How much did you pay in your meet-up? (AUD)" value={amount} onChange={setAmount} type="number" min="0.01" max="10000" step="0.01" required disabled={mutation.pending || uploading} /><Attachments context={{ parentKind: "expense", groupId: group.id }} files={files} onChange={setFiles} onBusy={setUploading} disabled={mutation.pending} label="Tax invoice *" /><ErrorNotice error={error || mutation.error} /></FieldGroup><div className="form-actions"><Button disabled={mutation.pending || uploading}>{mutation.pending ? "Submitting expense…" : "Submit expense"}</Button></div></form>;
}
