Match User mentor_origin_tunnel
    AuthenticationMethods publickey
    PubkeyAuthentication yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AuthorizedKeysFile /etc/mentor-portal-tunnel/authorized_keys
    AllowTcpForwarding remote
    AllowStreamLocalForwarding no
    GatewayPorts clientspecified
    PermitListen 172.30.253.1:13100
    PermitOpen none
    X11Forwarding no
    AllowAgentForwarding no
    PermitTTY no
    PermitUserRC no
    MaxSessions 0
Match all
